### ISSUE TITLE
Missing package.json?

### ISSUE THREAD

**Issue by scroobiustrip** [MarcusVirg/forty#10]
I'm having trouble getting forty to run properly with npm install + start; is this due to the lack of a package.json file or is there a way around using this? Many thanks.

**Comment by MarcusVirg** [comment]
Yes that is correct, I have not made this theme with support for Node and NPM, Hugo itself doesn't have a simple way to integrate node. It is possible to build Hugo with Node however. I would start with this guide:
How To Use NPM As A Build Tool With Hugo - The Codestead


| 
| 
|  | 
How To Use NPM As A Build Tool With Hugo - The Codestead

Hugo is a fast and all-around awesome tool for creating website. NPM has build-tool superpowers that folks seem ...
 |

 |

 |



This should allow you to get a start on getting this theme running correctly with Node.
    On Monday, February 26, 2018, 3:08:05 PM CST, scroobiustrip <notifications@github.com> wrote:  
 
 
I'm having trouble getting forty to run properly with npm install + start; is this due to the lack of a package.json file or is there a way around using this? Many thanks.
