### ISSUE TITLE
How to add <title></title>?

### ISSUE THREAD

**Issue by irmatable** [MarcusVirg/forty#4]
Can't figure out how to add the page title, for the site I'm using it's displaying all site tiles with a "." in the tab. 

Example here: https://elevatd.co/blogs/elevatdpod_00.md/

Any help would be appreciated on how to add that site title in the md blog file.

Thank you!

**Comment by MarcusVirg** [comment]
Hello Irma,
Yes this issue should have been fixed with the most recent commit for this theme. I had a syntax error when calling the header partial. When calling the header partial I had this: {{ partial "header.html" }}which is incorrect. This is the correct syntax: {{ partial "header.html" . }}   If you haven't pulled the latest changes from the forty repository just make sure you are calling the header partial correctly. As for the title front matter you can call it like this: <title>{{ if .Title }}{{ .Title }}{{ else }}{{ .Site.Title }}{{ end }}</title>If you want to see my site for an example of a working title check out the code at MarcusVirg/portfolio

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
MarcusVirg/portfolio

My personal portfolio site
 |

 |

 |



Let me know if this fixes your issue!    On Wednesday, January 10, 2018, 8:02:42 PM CST, Irma Mesa <notifications@github.com> wrote:  
 
 
Can't figure out how to add the page title, for the site I'm using it's displaying all site tiles with a "." in the tab.

Example here: https://elevatd.co/blogs/elevatdpod_00.md/

Any help would be appreciated on how to add that site title in the md blog file.

Thank you!

**Comment by MarcusVirg** [comment]
Also when browsing your site I see that you implemented Disqus which is great! Disqus works well with static sites. If you would like your comment section to have proper padding I would recommend wrapping your Disqus element inside of a div element with the class property set to `inner` like this:
```html
<div class="inner"><a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a></div>
```

**Comment by MorseGates** [comment]
Hi Marcus, forty is a just absolutely a great template and I am using it too. in looking at this site from safari web, I empty image boxes on each page. I have the same issue with my site as well. Do you have suggestions on how to fix this? I did send an email about this but, I guess posting it here would be the best way?
Thanks you!
Thanks

**Comment by MarcusVirg** [comment]
MorseGates,
I have created a new issue thread we can comment on. I will do some testing in Safari and post in that new thread with my solution to fixing the images. Thanks for using this theme.

**Comment by MorseGates** [comment]
Great,  and thanks for all the hard work on this project.
